version: "2.1"

services:
  mongo:
    image: mongo:latest
    container_name: userservicedb
    ports:
      - 27017:27017
  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080" # http port
      - "50051:50051" # grpc port
    environment:
      DB_URI: mongodb://mongo:27017/users
